<a href="https://colab.research.google.com/github/Nadun12Sandeepa/Next-Word-Prediction/blob/main/Next_Word_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf


In [2]:
with open("/content/cricket.txt.txt", 'r', encoding='utf-8') as file:
    cricket_history = file.read()

In [3]:

cricket_history[:500]

'Cricket history is particularly murky and vague as to the exact origins of the game, it is believed to have been born in England in the late middle ages.Add commentMore actions\n\nEdward III banned a game similar to cricket in 1369, ‘pila baculorea’ or ‘club ball’ as it was known, as he saw it as being a distraction to his war effort.\n\nDerek Birley in his wonderful book, ‘A Social History of English Cricket’ suggests the game came to England with the French during the time of the Norman Invasion, '

In [4]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts([cricket_history])


In [5]:
tokenizer.get_config()['filters']

'!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'

In [6]:
tokenizer.get_config()['word_counts']

'{"cricket": 35, "history": 2, "is": 8, "particularly": 2, "murky": 1, "and": 47, "vague": 1, "as": 25, "to": 45, "the": 148, "exact": 1, "origins": 1, "of": 48, "game": 22, "it": 22, "believed": 1, "have": 4, "been": 4, "born": 2, "in": 57, "england": 15, "late": 1, "middle": 1, "ages": 1, "add": 1, "commentmore": 1, "actions": 1, "edward": 3, "iii": 2, "banned": 1, "a": 22, "similar": 2, "1369": 1, "\\u2018pila": 1, "baculorea\\u2019": 1, "or": 5, "\\u2018club": 1, "ball\\u2019": 1, "was": 15, "known": 1, "he": 1, "saw": 7, "being": 8, "distraction": 1, "his": 2, "war": 1, "effort": 1, "derek": 1, "birley": 1, "wonderful": 1, "book": 1, "\\u2018a": 1, "social": 1, "english": 6, "cricket\\u2019": 3, "suggests": 1, "came": 1, "with": 16, "french": 1, "during": 2, "time": 5, "norman": 1, "invasion": 2, "that": 9, "their": 4, "word": 3, "\\u2018criquet\\u2019": 1, "dialect": 1, "name": 1, "for": 19, "variation": 1, "club": 4, "ball": 3, "had": 9, "sought": 2, "eradicate": 1, "there": 3, 

In [7]:
tokenizer.word_index


{'the': 1,
 'in': 2,
 'of': 3,
 'and': 4,
 'to': 5,
 'cricket': 6,
 'as': 7,
 'game': 8,
 'it': 9,
 'a': 10,
 'for': 11,
 'with': 12,
 'were': 13,
 'england': 14,
 'was': 15,
 'its': 16,
 'played': 17,
 'by': 18,
 'that': 19,
 'had': 20,
 'at': 21,
 'is': 22,
 'being': 23,
 'games': 24,
 'saw': 25,
 'they': 26,
 'new': 27,
 'australia': 28,
 'english': 29,
 'playing': 30,
 'first': 31,
 'an': 32,
 'be': 33,
 'between': 34,
 'from': 35,
 'technology': 36,
 'or': 37,
 'time': 38,
 'this': 39,
 'aristocracy': 40,
 'recorded': 41,
 'century': 42,
 'two': 43,
 'on': 44,
 'after': 45,
 'bowling': 46,
 'twenty': 47,
 'have': 48,
 'been': 49,
 'their': 50,
 'club': 51,
 'them': 52,
 'classes': 53,
 'teams': 54,
 'up': 55,
 'match': 56,
 'players': 57,
 'into': 58,
 'began': 59,
 'spread': 60,
 'south': 61,
 'international': 62,
 'only': 63,
 'edward': 64,
 'cricket’': 65,
 'word': 66,
 'ball': 67,
 'there': 68,
 'play': 69,
 'men': 70,
 'way': 71,
 'seen': 72,
 'side': 73,
 'best': 74,
 'becom

In [8]:
input_sequences = []
for sentence in cricket_history.split('\n'):
    token_list = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(token_list)):
        sequence = token_list[:i+1]
        input_sequences.append(sequence)

In [9]:

input_sequences[:5]

[[6, 93],
 [6, 93, 22],
 [6, 93, 22, 94],
 [6, 93, 22, 94, 178],
 [6, 93, 22, 94, 178, 4]]

In [10]:
max_length = max([len(input_sequence) for input_sequence in input_sequences])
max_length

55

In [11]:
input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding='pre'))


In [12]:
input_sequences[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  6, 93, 22], dtype=int32)

In [13]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [14]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 6], dtype=int32)

In [15]:
y

array([ 93,  22,  94, ...,  38, 177, 625], dtype=int32)

In [16]:
num_classes = len(tokenizer.word_index)+1

In [17]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=num_classes))

In [18]:
y[1]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [19]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(num_classes, 80, input_length=max_length-1))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:


model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [22]:
history = model.fit(X, y, epochs=100)

Epoch 1/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.0328 - loss: 6.3218
Epoch 2/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.0938 - loss: 5.6259
Epoch 3/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.0933 - loss: 5.5008
Epoch 4/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 57ms/step - accuracy: 0.0948 - loss: 5.4792
Epoch 5/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - accuracy: 0.1075 - loss: 5.3747
Epoch 6/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 5s 51ms/step - accuracy: 0.1013 - loss: 5.2217
Epoch 7/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.1036 - loss: 5.2161
Epoch 8/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.0948 - loss: 5.1640
Epoch 9/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 4s 68ms/step - accuracy: 0.1287 - loss: 4.9758
Epoch 10/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.1215 - loss: 4.8723
Epoch 11/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.1224 - loss: 4.8053
Epoch 12/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step

In [23]:
input_text = "cricket begin"
for i in range(6):
    token_list = tokenizer.texts_to_sequences([input_text])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 250ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
cricket begin the game continued to spread through
